language: python
cache: pip

python:
  - pypy3
  - nightly
  - 3.10-dev
  - 3.9
  - 3.8
  - 3.7
  - 3.6

# whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
  - travis_retry pip install -U flake8

script:
    # Static analysis
  - flake8 .

matrix:
  fast_finish: true
